server:
  port: 10080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8002/eureka/

spring:
  application:
    name: zuul
    
logging:  file: logback.xml

zuul: 
  routes:
    consumer:
       serviceId: client-consumer
       path: /zuul-consumer/**
    provider:
       serviceId: client-provider
       path: /zuul-provider/**
    config:
       serviceId: config-server
       path: /zuul-config/**
  ignored-services: '*'
