server:
  port: 10080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8002/eureka/

spring:
  application:
    name: zuul
    
logging:  file: logback.xml

zuul: 
  routes:
    consumer.serviceId: client-consumer
    consumer.path: /zuul-consumer/**