server:
  port: 20080

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/870235784/springcloud-config.git   # 配置git仓库的地址
          search-paths: properties                             # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: 870235784@qq.com                           # git仓库的账号
          password:                                            # git仓库的密码

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/

logging:
  file: logback.xml
  
 
  
