server:
  port: 7001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/

spring:
  application:
    name: client-consumer
    
logging:  file: logback.xml

