server:
  port: 8001

spring:
  application:
    name: client-provider

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

logging:
  file: logback.xml
  
