server:
  port: 9001

spring:
  application:
    name: client-provider

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/

logging:
  file: logback.xml
  
